### ISSUE TITLE
Showing Program addons instead of a folder or shortcut destination on Arch linux

### ISSUE THREAD

**Issue by cg00001** [jmooremcc/Repository.jmooremcc#6]
Sometimes SF links would work, other times the Program addons would only show.
I've never heard of this happening anywhere else than Linux.
This is the reason a while ago I stopped using SF and only use Autowidget for my shortcut groups and links.
Is there any possibility of a fix?
Sorry, haven't kept a log.

**Comment by jmooremcc** [comment]
I need to see a debug log in order to address the issue. Don't forget to turn on debugging in the SF settings.



Sent from my Galaxy



-------- Original message --------
From: csts ***@***.***>
Date: 8/2/22 8:13 AM (GMT-05:00)
To: "jmooremcc/Repository.jmooremcc" ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jmooremcc/Repository.jmooremcc] Showing Program addons instead of a folder or shortcut destination on Arch linux (Issue #6)


Sometimes SF links would work, other times the Program addons would only show.
I've never heard of this happening anywhere else than Linux.
This is the reason a while ago I stopped using SF and only use Autowidget for my shortcut groups and links.
Is there any possibility of a fix?
Sorry, haven't kept a log.

**Comment by cg00001** [comment]
I made two SF links to Asgard and Black Lightning and placed them in a section in Titan M O D skin.
Then started opening them one by one (going back to menu with ESC) and 2 times the links failed showing only the section this time (no Program addons).
I think the first is in line 3059.
[kodi.log](https://github.com/jmooremcc/Repository.jmooremcc/files/9242349/kodi.log)

**Comment by cg00001** [comment]
New version fixed the issue.
